name: 'webqsp'
data_folder: 'datasets/webqsp/full/'
train_data: 'train.json'
train_documents: 'documents.json'
dev_data: 'dev.json'
dev_documents: 'documents.json'
test_data: 'test.json'
test_documents: 'documents.json'

word2id: 'vocab.txt'
relation2id: 'relations.txt'
entity2id: 'entities.txt'
word_emb_file: "word_emb_100d.npy"
entity_emb_file: "entity_emb_100d.npy"
entity_kge_file: "entity_kge_100d.npy"
relation_emb_file: "relation_emb_100d.npy"
relation_kge_file: "relation_kge_100d.npy"

to_save_model: True
save_model_file: "repro/webqsp/best_model_kg"
pred_file: "repro/webqsp/pred_kg"
load_model_file:

# graph options
fact_dropout: 0.1
use_kb: True
use_doc: False

num_layer: 3
max_query_word: 10
max_document_word: 50

entity_dim: 50
word_dim: 100
kge_dim: 100
pagerank_lambda: 0.8
fact_scale: 3
use_inverse_relation: False

# optimization
num_epoch: 50
batch_size: 30
gradient_clip: 1
learning_rate: 0.001
lstm_dropout: 0.3
linear_dropout: 0.2
is_debug: False

# device
gpu_id: 1
